export const ru = {
  // Навигация
  app_title: "Салон CRM",
  dashboard: "Панель управления",
  clients: "Клиенты",
  employees: "Сотрудники",
  services: "Услуги",
  appointments: "Записи",
  finance: "Финансы",
  inventory: "Склад",
  branches: "Филиалы",
  settings: "Настройки",
  super_admin: "Super Админ",

  // Авторизация и Общее
  login_title: "Войдите в систему управления",
  login_submit: "Войти",
  email_or_phone: "Email или телефон",
  password: "Пароль",
  save: "Сохранить",
  cancel: "Отмена",
  error: "Ошибка",
  not_found: "Не найдено",
  status: "Статус",
  active: "Активен",
  inactive: "Неактивен",
  user: "Пользователь",
  admin: "Администратор",
  session_expiring_soon: "Сессия истечет скоро",

  // Дашборд
  total_clients: "Всего клиентов",
  today_appointments: "Записи сегодня",
  weekly_revenue: "Выручка за неделю",
  staff_utilization: "Загруженность",
  revenue_trend: "Динамика дохода",
  upcoming_appointments: "Ближайшие записи",
  no_appointments_today: "Нет записей на сегодня",
  week_change: "за неделю",
  from_average: "от среднего",
  from_last_week: "от прошлой недели",

  // Клиенты
  title_clients: "Клиенты",
  add_client: "Добавить клиента",
  search_clients_placeholder: "Поиск по имени или телефону...",
  filters: "Фильтры",
  client_name: "Имя",
  client_phone: "Телефон",
  client_email_optional: "Email (необязательно)",
  table_name: "Имя",
  table_phone: "Телефон",
  table_visits: "Посещений",
  table_last_service: "Последняя услуга",
  table_bonus_balance: "Баланс бонусов",
  no_clients: "Нет зарегистрированных клиентов",

  // Склад (Inventory)
  title_inventory: "Склад",
  add_material: "Добавить материал",
  add_new_material: "Добавить новый материал",
  total_items: "Всего материалов",
  low_stock: "Низкий остаток",
  out_of_stock: "Закончилось",
  in_stock: "В наличии",
  search_inventory_placeholder: "Поиск материалов...",
  general_stock: "Общий склад",
  mat_name: "Название материала",
  quantity: "Количество",
  unit: "Единица измерения",
  min_quantity: "Минимальное количество",
  branch: "Филиал",
  unknown_branch: "Неизвестный филиал",
  inventory_not_found: "Материалы не найдены",
  no_inventory: "Нет добавленных материалов",
  inventory_added_title: "Материал добавлен",
  inventory_added_desc: "Новый материал успешно добавлен на склад",
  inventory_add_failed: "Не удалось добавить материал",
  inventory_deleted_title: "Материал удален",
  inventory_deleted_desc: "Материал успешно удален со склада",
  inventory_delete_failed: "Не удалось удалить материал",
  confirm_delete_inventory: "Вы уверены, что хотите удалить этот материал?",
  choose_unit: "Выберите единицу",

  // Сотрудники и Филиалы
  title_employees: "Сотрудники",
  add_employee: "Добавить сотрудника",
  search_employees_placeholder: "Поиск по имени или должности...",
  employee_name: "Имя",
  employee_position: "Должность",
  employee_phone: "Телефон",
  employee_branch: "Филиал",
  employee_status: "Статус",
  no_employees: "Нет зарегистрированных сотрудников",
  employees_not_found: "Сотрудники не найдены",
  title_branches: "Филиалы",
  add_branch: "Добавить филиал",
  branch_name: "Название филиала",
  branch_address: "Адрес",
  choose_branch: "Выберите филиал",

  // Услуги и Записи
  title_services: "Услуги",
  add_service: "Добавить услугу",
  service_name: "Название услуги",
  description: "Описание",
  duration_minutes: "Длительность (минуты)",
  price_rub: "Цена (сум)",
  category: "Категория",
  all_services: "Все услуги",
  search_services_placeholder: "Поиск услуг...",
  no_services: "Нет добавленных услуг",
  title_appointments: "Календарь записей",
  new_appointment: "Новая запись",
  client: "Клиент",
  service: "Услуга",
  master: "Мастер",
  date_time: "Дата и время",
  choose_master: "Выберите мастера",
  choose_service: "Выберите услугу",
  choose_client: "Выберите клиента",
  add_appointment: "Добавить запись",

  // Финансы
  title_finance: "Финансы",
  export: "Экспорт",
  overall_revenue: "Общая выручка",
  today_revenue: "Выручка сегодня",
  payment_method: "Способ оплаты",
  cash: "Наличные",
  card: "Карта",
  completed: "Завершен",
  processing: "В обработке",
  no_payments: "Нет платежей для отображения",

  // Календарь
  all_branches_placeholder: "Все филиалы",
  all_masters_placeholder: "Все мастера",
  view_day: "День",
  view_week: "Неделя",
  schedule_for_day: "Расписание на день",
  no_appointments_date: "На эту дату нет записей",
  quick_actions: "Быстрые действия",
  see_week: "Посмотреть неделю",
  day_stats: "Статистика дня",
  total_appointments_label: "Всего записей",
  completed_label: "Завершено",
  scheduled_label: "Запланировано",
  revenue_label: "Выручка",
  uz_cash: "Наличные (UZS)",
  uz_card: "Карта (Humo/Uzcard)",
  uz_online: "Онлайн",
  online: "Онлайн",
  week: "Неделя",
  month: "Месяц",
  payments_count: "Количество платежей",
  total_operations: "Всего операций",
  revenue_dynamics: "Динамика выручки",
  payment_methods: "Способы оплаты",
  payments_history: "История платежей",
  all_methods: "Все способы",
  date: "Дата",
  client_col: "Клиент",
  service_col: "Услуга",
  amount: "Сумма",
  categories: "Категории",
  services_not_found: "Услуги не найдены",
};