export const uz = {
  // Navigatsiya
  app_title: "Salon CRM",
  dashboard: "Boshqaruv paneli",
  clients: "Mijozlar",
  employees: "Xodimlar",
  services: "Xizmatlar",
  appointments: "Qabul",
  finance: "Moliya",
  inventory: "Ombor",
  branches: "Filiallar",

  // Avtorizatsiya va Umumiy
  login_title: "Tizimga kirish",
  login_submit: "Kirish",
  email_or_phone: "Email yoki telefon",
  password: "Parol",
  save: "Saqlash",
  cancel: "Bekor qilish",
  error: "Xato",
  not_found: "Topilmadi",
  status: "Holat",
  active: "Faol",
  inactive: "Nofaol",
  user: "Foydalanuvchi",
  admin: "Administrator",
  session_expiring_soon: "Sessiya tez orada tugaydi",

  // Dashboard
  total_clients: "Jami mijozlar",
  today_appointments: "Bugungi qabul",
  weekly_revenue: "Haftalik daromad",
  staff_utilization: "Bandlik darajasi",
  revenue_trend: "Daromad dinamikasi",
  upcoming_appointments: "Yaqin qabul",
  no_appointments_today: "Bugun qabul yo'q",
  week_change: "hafta bo'yicha",
  from_average: "o'rtacha bo'yicha",
  from_last_week: "o'tgan haftadan",

  // Mijozlar
  title_clients: "Mijozlar",
  add_client: "Mijoz qo'shish",
  search_clients_placeholder: "Ism yoki telefon bo'yicha qidirish...",
  filters: "Filtrlar",
  client_name: "Ism",
  client_phone: "Telefon",
  client_email_optional: "Email (majburiy emas)",
  table_name: "Nomi",
  table_phone: "Telefon",
  table_visits: "Tashriflar",
  table_last_service: "Oxirgi xizmat",
  table_bonus_balance: "Bonus balansi",
  no_clients: "Mijozlar mavjud emas",

  // Ombor (Inventory)
  title_inventory: "Ombor",
  add_material: "Material qo'shish",
  add_new_material: "Yangi material qo'shish",
  total_items: "Jami materiallar",
  low_stock: "Kam qoldi",
  out_of_stock: "Tugagan",
  in_stock: "Mavjud",
  search_inventory_placeholder: "Materiallarni qidirish...",
  general_stock: "Umumiy ombor",
  mat_name: "Material nomi",
  quantity: "Miqdor",
  unit: "O'lchov birligi",
  min_quantity: "Minimal miqdor",
  branch: "Filial",
  unknown_branch: "Noma'lum filial",
  inventory_not_found: "Materiallar topilmadi",
  no_inventory: "Materiallar qo'shilmagan",
  inventory_added_title: "Material qo'shildi",
  inventory_added_desc: "Yangi material omborga qo'shildi",
  inventory_add_failed: "Materialni qo'shish muvaffaqiyatsiz",
  inventory_deleted_title: "Material o'chirildi",
  inventory_deleted_desc: "Material ombordan o'chirildi",
  inventory_delete_failed: "Materialni o'chirish muvaffaqiyatsiz",
  confirm_delete_inventory: "Ushbu materialni o'chirmoqchimisiz?",
  choose_unit: "Birlikni tanlang",

  // Xodimlar va Filiallar
  title_employees: "Xodimlar",
  add_employee: "Xodim qo'shish",
  search_employees_placeholder: "Ism yoki lavozim bo'yicha qidirish...",
  employee_name: "Ism",
  employee_position: "Lavozim",
  employee_phone: "Telefon",
  employee_branch: "Filial",
  employee_status: "Holat",
  no_employees: "Xodimlar mavjud emas",
  employees_not_found: "Xodimlar topilmadi",
  title_branches: "Filiallar",
  add_branch: "Filial qo'shish",
  branch_name: "Filial nomi",
  branch_address: "Manzil",
  choose_branch: "Filialni tanlang",

  // Xizmatlar va Qabul
  title_services: "Xizmatlar",
  add_service: "Xizmat qo'shish",
  service_name: "Xizmat nomi",
  description: "Tavsif",
  duration_minutes: "Davomiyligi (daqiqa)",
  price_rub: "Narxi (so'm)",
  category: "Kategoriya",
  all_services: "Barcha xizmatlar",
  search_services_placeholder: "Xizmatlarni qidirish...",
  no_services: "Xizmatlar qo'shilmagan",
  title_appointments: "Qabul taqvimi",
  new_appointment: "Yangi qabul",
  client: "Mijoz",
  service: "Xizmat",
  master: "Usta",
  date_time: "Sana va vaqt",
  choose_master: "Ustani tanlang",
  choose_service: "Xizmatni tanlang",
  choose_client: "Mijozni tanlang",
  add_appointment: "Qabul qo'shish",

  // Moliya
  title_finance: "Moliya",
  export: "Eksport",
  overall_revenue: "Umumiy daromad",
  today_revenue: "Bugungi daromad",
  payment_method: "To'lov usuli",
  cash: "Naqd",
  card: "Karta",
  completed: "Tugallangan",
  processing: "Jarayonda",
  no_payments: "Ko'rsatish uchun to'lovlar yo'q",
};